# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: cmake-vcpkg-build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  # Path to the solution file relative to the root of the project.
  SOLUTION_FILE_PATH: .

  # Configuration type to build.
  # You can convert this to a build matrix if you need coverage of multiple configuration types.
  # https://docs.github.com/actions/learn-github-actions/managing-complex-workflows#using-a-build-matrix
  BUILD_CONFIGURATION: Release

permissions:
  contents: read

jobs:
  job:
    name: ${{ matrix.os }}-${{ github.workflow }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [windows-latest]
        include:
          - os: windows-latest
            triplet: x64-windows
            
    env:
      VCPKG_DEFAULT_TRIPLET: ${{ matrix.triplet }}

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4
      with:
        submodules: true

    - name: Use Developer PowerShell
      run: |
        vsInstallPath = "C:\Program Files\Microsoft Visual Studio\2022\Enterprise"
        $devShellModule = "$vsInstallPath\Common7\Tools\Microsoft.VisualStudio.DevShell.dll"
        Import-Module $devShellModule
        Enter-VsDevShell -VsInstallPath $vsInstallPath -Arch amd64 -SkipAutomaticLocation
        cmake --workflow --preset x64-release
      shell: pwsh


